# Generated by Django 2.2 on 2019-05-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_auto_20190426_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='tip',
            field=models.FloatField(),
        ),
    ]
